# Generated by Django 4.2.7 on 2024-07-05 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_userorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='cart_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='items',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiserver.cart'),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
