# Generated by Django 4.2.7 on 2024-07-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_userorders_cart_snapshot_alter_userorders_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cususer',
            name='profile',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
