# Generated by Django 4.2.7 on 2024-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0005_rename_profile_cususer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cususer',
            name='profile_image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
